FROM azul/zulu-openjdk:21-jre
RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY server-all.jar /app/server-all.jar
ENTRYPOINT ["java", "-Xmx512m", "-jar", "/app/server-all.jar"]
